## Representaciónes de números en computación


Los números que puede representar (almacenar en su memoria) una computadora  son un conjunto finito, están dados por el tamaño de la memoria que elijamos para almacenar cada uno de ellos. Pero esto se puede hacer de distintas formas. 

En Julia el tipo de represen tación de cada número no es fijo y puede cambiar dinámicamente, o sea puede cambiar mientras el problema se ejecuta. Eso permite mucha flexibilidad, pero también hay que entender bien cómo funciona. Para ello utilizaremos dos comandos muy interesantes: `typeof` que nos dice que tipo de variable tenemos y `bitstring` que nos dice cómo es la representación de cada número en memoria, lo cual se hace en la representación 2. Veamos algunos ejemplos:



### Representación de enteros

In [56]:
uno = 1

1

In [57]:
typeof(uno)

Int64

In [59]:
bitstring(2)

"0000000000000000000000000000000000000000000000000000000000000010"

In [67]:
bitstring(-34567)

"1111111111111111111111111111111111111111111111110111100011111001"

In [61]:
bitstring(2^(64))

"0000000000000000000000000000000000000000000000000000000000000000"

In [65]:
2.0 ^(64)

1.8446744073709552e19

In [10]:
uno_corto = Int8(1)

1

In [11]:
typeof(uno_corto)

Int8

In [12]:
bitstring(uno_corto)

"00000001"

Cuál es el número más grande?

In [68]:
2^8

256

In [73]:
Int8(2^6)
#mayor_8::Int8 = 2^8
Int8(90)

90

El tipo por defecto es Int64. Cuál será el número más grande que podemos representar?

Operaciones en enteros

In [74]:
Int8(90) + Int8(90)

-76

In [26]:
5 ÷ 2 #división entera \div o \div TAB> 

2

In [77]:
5 ÷ 2

LoadError: syntax: extra token "div" after end of expression

In [75]:
5 / 2

2.5

### Racionales

In [81]:
uno_r = 1//1
typeof(1//1)

Rational{Int64}

In [79]:
1//2 + 5//3

13//6

In [84]:
bitstring(1//3)

LoadError: MethodError: no method matching bitstring(::Rational{Int64})
Closest candidates are:
  bitstring(::Union{Bool, Int8, UInt8}) at intfuncs.jl:729
  bitstring(::Union{Float16, Int16, UInt16}) at intfuncs.jl:730
  bitstring(::Union{Char, Float32, Int32, UInt32}) at intfuncs.jl:731
  ...

In [86]:
typeof(1/3)

Float64

In [89]:
tres_b = BigFloat(3)

3.0

In [90]:
1/tres_b

0.3333333333333333333333333333333333333333333333333333333333333333333333333333348

### Punto Flotante

In [36]:
typeof(1.)

Float64

In [48]:
subtypes(AbstractFloat)

4-element Array{Any,1}:
 BigFloat
 Float16
 Float32
 Float64

In [37]:
bitstring(1.0)

"0011111111110000000000000000000000000000000000000000000000000000"

In [91]:
bitstring(2)

"0000000000000000000000000000000000000000000000000000000000000010"

Cuál es el número más pequeño que puedo representar? 

In [92]:
eps(0.)

5.0e-324

Cuál es el número más cercano a 1.?

In [41]:
eps(1.)

2.220446049250313e-16

In [42]:
1. == 1. + eps(1.)

false

In [43]:
1. == 1. + 0.5 * eps(1.)

true

### Otros tipos:

In [93]:
uno_s = "uno"

"uno"

In [94]:
typeof(uno_s)

String

In [95]:
dos_s = "dos"

"dos"

In [96]:
uno_s * dos_s

"unodos"

In [99]:
dos_s * " " * uno_s

"dos uno"

In [106]:
calecita = zeros(6,3)

6×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [103]:
muchos_unos = ones(2,3,4)

2×3×4 Array{Float64,3}:
[:, :, 1] =
 1.0  1.0  1.0
 1.0  1.0  1.0

[:, :, 2] =
 1.0  1.0  1.0
 1.0  1.0  1.0

[:, :, 3] =
 1.0  1.0  1.0
 1.0  1.0  1.0

[:, :, 4] =
 1.0  1.0  1.0
 1.0  1.0  1.0

In [101]:
muchos_unos * unos

2-element Array{Float64,1}:
 3.0
 3.0

In [107]:
uno

1

In [108]:
uno = uno +1

2

In [109]:
uno

2