## Urgando en Julia

### Cómo obtener información de nuestro código


Aquí vamos a ver distintas maneras de obtener información sobre nuestro código, ya sea estática o dinámica.

### Información sobre variables

Comenzamos con el comando `typeof`la cual nos dice de que tipo es una dada variable.

In [ ]:
uno = 1
typeof(one)

In [3]:
uno = 1.
typeof(uno)

Float64

In [4]:
uno = 1//1
typeof(uno)

Rational{Int64}

In [37]:
uno = 1 + im*0
typeof(uno)

Complex{Int64}

In [38]:
uno = "uno"
typeof(uno)

String

In [39]:
?ones

search: ones leading_ones trailing_ones countlines count_ones to_indices



```
ones([T=Float64,] dims::Tuple)
ones([T=Float64,] dims...)
```

Create an `Array`, with element type `T`, of all ones with size specified by `dims`. See also: [`fill`](@ref), [`zeros`](@ref).

# Examples

```jldoctest
julia> ones(1,2)
1×2 Array{Float64,2}:
 1.0  1.0

julia> ones(ComplexF64, 2, 3)
2×3 Array{Complex{Float64},2}:
 1.0+0.0im  1.0+0.0im  1.0+0.0im
 1.0+0.0im  1.0+0.0im  1.0+0.0im
```


In [40]:
unos = ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [41]:
typeof(unos)

Array{Float64,1}

In [46]:
muchos = fill(3*unos,2,3)

2×3 Array{Array{Float64,1},2}:
 [1.0, 1.0, 1.0]  [1.0, 1.0, 1.0]  [1.0, 1.0, 1.0]
 [1.0, 1.0, 1.0]  [1.0, 1.0, 1.0]  [1.0, 1.0, 1.0]

In [47]:
matriz = fill(uno,2,3)

2×3 Array{String,2}:
 "uno"  "uno"  "uno"
 "uno"  "uno"  "uno"

In [48]:
subtypes(AbstractFloat)

4-element Array{Any,1}:
 BigFloat
 Float16
 Float32
 Float64

In [57]:
typeof(typeof(1))

DataType

In [60]:
typeof(Base)

Module

### Información sobre funciones

In [11]:
@which sin #en que librería está

Base

In [12]:
?sin

search: sin sinh sind sinc sinpi sincos sincosd asin using isinf asinh asind



```
sin(x)
```

Compute sine of `x`, where `x` is in radians.

---

```
sin(A::AbstractMatrix)
```

Compute the matrix sine of a square matrix `A`.

If `A` is symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the sine. Otherwise, the sine is determined by calling [`exp`](@ref).

# Examples

```jldoctest
julia> sin(fill(1.0, (2,2)))
2×2 Array{Float64,2}:
 0.454649  0.454649
 0.454649  0.454649
```


In [13]:
methods(sin)

# 13 methods for generic function "sin":
[1] sin(x::BigFloat) in Base.MPFR at mpfr.jl:727
[2] sin(::Missing) in Base.Math at math.jl:1197
[3] sin(a::Complex{Float16}) in Base.Math at math.jl:1145
[4] sin(a::Float16) in Base.Math at math.jl:1144
[5] sin(z::Complex{T}) where T in Base at complex.jl:804
[6] sin(x::T) where T<:Union{Float32, Float64} in Base.Math at special/trig.jl:29
[7] sin(x::Real) in Base.Math at special/trig.jl:53
[8] sin(A::LinearAlgebra.Hermitian{var"#s827",S} where S<:(AbstractArray{var"#s828",2} where var"#s828"<:var"#s827") where var"#s827"<:Complex) in LinearAlgebra at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/LinearAlgebra/src/symmetric.jl:922
[9] sin(A::Union{LinearAlgebra.Hermitian{var"#s828",S}, LinearAlgebra.Symmetric{var"#s828",S}} where S where var"#s828"<:Real) in LinearAlgebra at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/LinearAlgebra/src/symmetric.jl:918
[10] sin(D::LinearAlgebra.Diagonal) in LinearAlgebra at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/LinearAlgebra/src/diagonal.jl:576
[11] sin(A::AbstractArray{var"#s828",2} where var"#s828"<:Real) in LinearAlgebra at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/LinearAlgebra/src/dense.jl:836
[12] sin(A::AbstractArray{var"#s828",2} where var"#s828"<:Complex) in LinearAlgebra at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/LinearAlgebra/src/dense.jl:843
[13] sin(J::LinearAlgebra.UniformScaling) in LinearAlgebra at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/LinearAlgebra/src/uniformscaling.jl:139

In [14]:
methods(*)

# 364 methods for generic function "*":
[1] *(x::Float32, y::Float32) in Base at float.jl:404
[2] *(a::Float16, b::Float16) in Base at float.jl:398
[3] *(z::Complex{Bool}, x::Bool) in Base at complex.jl:291
[4] *(z::Complex{Bool}, x::Real) in Base at complex.jl:309
[5] *(r::Regex) in Base at regex.jl:677
[6] *(::Missing, ::Missing) in Base at missing.jl:114
[7] *(::Missing, ::Number) in Base at missing.jl:115
[8] *(d::Missing, x::AbstractString) in Base at missing.jl:174
[9] *(x::Float64, y::Float64) in Base at float.jl:405
[10] *(x::Bool, z::Complex{Bool}) in Base at complex.jl:290
[11] *(x::Bool, y::Bool) in Base at bool.jl:98
[12] *(x::Bool, y::T) where T<:AbstractFloat in Base at bool.jl:109
[13] *(x::Bool, z::Complex) in Base at complex.jl:297
[14] *(x::Bool, y::AbstractIrrational) in Base at irrationals.jl:158
[15] *(B::BitArray{2}, J::LinearAlgebra.UniformScaling) in LinearAlgebra at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/LinearAlgebra/src/uniformscaling.jl:224
[16] *(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat, e::BigFloat) in Base.MPFR at mpfr.jl:548
[17] *(a::BigFloat, b::BigFloat, c::BigFloat, d::BigFloat) in Base.MPFR at mpfr.jl:541
[18] *(a::BigFloat, b::BigFloat, c::BigFloat) in Base.MPFR at mpfr.jl:535
[19] *(x::BigFloat, c::BigInt) in Base.MPFR at mpfr.jl:394
[20] *(x::BigFloat, y::BigFloat) in Base.MPFR at mpfr.jl:363
[21] *(x::BigFloat, c::Union{UInt16, UInt32, UInt64, UInt8}) in Base.MPFR at mpfr.jl:370
[22] *(x::BigFloat, c::Union{Int16, Int32, Int64, Int8}) in Base.MPFR at mpfr.jl:378
[23] *(x::BigFloat, c::Union{Float16, Float32, Float64}) in Base.MPFR at mpfr.jl:386
[24] *(this::Base.Grisu.Float, other::Base.Grisu.Float) in Base.Grisu at grisu/float.jl:139
[25] *(c::BigInt, x::BigFloat) in Base.MPFR at mpfr.jl:399
[26] *(a::BigInt, b::BigInt, c::BigInt, d::BigInt, e::BigInt) in Base.GMP at gmp.jl:518
[27] *(a::BigInt, b::BigInt, c::BigInt, d::BigInt) in Base.GMP at gmp.jl:517
[28] *(a::BigInt, b::BigInt, c::BigInt) in Base.GMP at gmp.jl:516
[29] *(x::BigInt, y::BigInt) in Base.GMP at gmp.jl:476
[30] *(x::BigInt, c::Union{UInt16, UInt32, UInt64, UInt8}) in Base.GMP at gmp.jl:535
[31] *(x::BigInt, c::Union{Int16, Int32, Int64, Int8}) in Base.GMP at gmp.jl:537
[32] *(y::AbstractFloat, x::Bool) in Base at bool.jl:112
[33] *(x::T, y::T) where T<:Union{Int128, UInt128} in Base at int.jl:907
[34] *(x::T, y::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} in Base at int.jl:87
[35] *(c::Union{UInt16, UInt32, UInt64, UInt8}, x::BigInt) in Base.GMP at gmp.jl:536
[36] *(c::Union{Int16, Int32, Int64, Int8}, x::BigInt) in Base.GMP at gmp.jl:538
[37] *(a::Integer, b::Integer) in Base at int.jl:918
[38] *(x::Real, r::StepRangeLen{var"#s91",var"#s90",S} where S where var"#s90"<:Base.TwicePrecision where var"#s91"<:Real) in Base at twiceprecision.jl:485
[39] *(z::Complex, w::Complex) in Base at complex.jl:277
[40] *(z::Complex, x::Bool) in Base at complex.jl:298
[41] *(x::Real, z::Complex{Bool}) in Base at complex.jl:308
[42] *(x::Real, z::Complex) in Base at complex.jl:320
[43] *(z::Complex, x::Real) in Base at complex.jl:321
[44] *(x::Rational, y::Rational) in Base at rational.jl:307
[45] *(x::Rational, y::Integer) in Base at rational.jl:312
[46] *(y::Integer, x::Rational) in Base at rational.jl:316
[47] *(a::Integer, index::CartesianIndex{N}) where N in Base.IteratorsMD at multidimensional.jl:122
[48] *(c::Union{UInt16, UInt32, UInt64, UInt8}, x::BigFloat) in Base.MPFR at mpfr.jl:375
[49] *(c::Union{Int16, Int32, Int64, Int8}, x::BigFloat) in Base.MPFR at mpfr.jl:383
[50] *(c::Union{Float16, Float32, Float64}, x::BigFloat) in Base.MPFR at mpfr.jl:391
[51] *(x::AbstractIrrational, y::AbstractIrrational) in Base at irrationals.jl:156
[52] *(y::Real, x::Dates.Period) in Dates at /Applications/Julia-1.5.app/Contents/Resources/julia/share/julia/stdlib/v1.5/Dates/src/periods.jl:94
[53] *(x::Real, A::LinearAlgebra.Hermitian) in LinearAlg

In [61]:
*(2,2)

4

In [79]:
A = fill(1.,2,2)

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [80]:
x = ones(2)

2-element Array{Float64,1}:
 1.0
 1.0

In [81]:
A*x

2-element Array{Float64,1}:
 2.0
 2.0

### Tiempos de ejecución / uso de memoria

In [15]:
function suma(N)
    s = 0
    for i ∈ 1:N
        s = s + rand()/i
    end
    return s
end

println(suma(10000000))

@time suma(10000000)

8.37891105130741
  0.042967 seconds


7.775224075844351

In [16]:
N = 10^6
s = 0
@time begin
    for i ∈ 1:N
        s = s + rand()/i
    end
end

  0.215967 seconds (6.00 M allocations: 106.801 MiB, 13.79% gc time)


In [17]:
@timev rand(10^6);

  0.015756 seconds (2 allocations: 7.629 MiB, 65.01% gc time)
elapsed time (ns): 15756424
gc time (ns):      10243553
bytes allocated:   8000080
pool allocs:       1
malloc() calls:    1
GC pauses:         1


In [18]:
using BenchmarkTools

In [19]:
@benchmark rand(10^6)

BenchmarkTools.Trial: 
  memory estimate:  7.63 MiB
  allocs estimate:  2
  --------------
  minimum time:     981.039 μs (0.00% GC)
  median time:      1.313 ms (0.00% GC)
  mean time:        1.828 ms (31.00% GC)
  maximum time:     59.499 ms (98.55% GC)
  --------------
  samples:          2736
  evals/sample:     1

### Compilaciones intermedias

In [62]:
@code_llvm 1 + 3


;  @ int.jl:86 within `+'
define i64 @"julia_+_2814"(i64, i64) {
top:
  %2 = add i64 %1, %0
  ret i64 %2
}


In [20]:
@code_llvm +(1,3)


;  @ int.jl:86 within `+'
define i64 @"julia_+_2099"(i64, i64) {
top:
  %2 = add i64 %1, %0
  ret i64 %2
}


In [21]:
@code_llvm +(1,3.)


;  @ promotion.jl:311 within `+'
define double @"julia_+_2100"(i64, double) {
top:
; ┌ @ promotion.jl:282 within `promote'
; │┌ @ promotion.jl:259 within `_promote'
; ││┌ @ number.jl:7 within `convert'
; │││┌ @ float.jl:60 within `Float64'
      %2 = sitofp i64 %0 to double
; └└└└
;  @ promotion.jl:311 within `+' @ float.jl:401
  %3 = fadd double %2, %1
;  @ promotion.jl:311 within `+'
  ret double %3
}


### Sobre la versión de Julia

In [22]:
using InteractiveUtils
versioninfo()

Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)


### Sobre versiones de los paquetes

In [23]:
using Pkg
Pkg.status("InteractiveUtils")
#Pkg.status("Plots")

No Matches in `~/.julia/environments/v1.5/Project.toml`


In [29]:
?Pkg.add

```
Pkg.add(pkg::Union{String, Vector{String}}; preserve=PRESERVE_TIERED)
Pkg.add(pkg::Union{PackageSpec, Vector{PackageSpec}}; preserve=PRESERVE_TIERED)
```

Add a package to the current project. This package will be available by using the `import` and `using` keywords in the Julia REPL, and if the current project is a package, also inside that package.

## Resolution Tiers

`Pkg` resolves the set of packages in your environment using a tiered algorithm. The `preserve` keyword argument allows you to key into a specific tier in the resolve algorithm. The following table describes the argument values for `preserve` (in order of strictness):

| Value             | Description                                                                         |
|:----------------- |:----------------------------------------------------------------------------------- |
| `PRESERVE_ALL`    | Preserve the state of all existing dependencies (including recursive dependencies)  |
| `PRESERVE_DIRECT` | Preserve the state of all existing direct dependencies                              |
| `PRESERVE_SEMVER` | Preserve semver-compatible versions of direct dependencies                          |
| `PRESERVE_NONE`   | Do not attempt to preserve any version information                                  |
| `PRESERVE_TIERED` | Use the tier which will preserve the most version information (this is the default) |

# Examples

```julia
Pkg.add("Example") # Add a package from registry
Pkg.add("Example"; preserve=Pkg.PRESERVE_ALL) # Add the `Example` package and preserve existing dependencies
Pkg.add(name="Example", version="0.3") # Specify version; latest release in the 0.3 series
Pkg.add(name="Example", version="0.3.1") # Specify version; exact release
Pkg.add(url="https://github.com/JuliaLang/Example.jl", rev="master") # From url to remote gitrepo
Pkg.add(url="/remote/mycompany/juliapackages/OurPackage") # From path to local gitrepo
Pkg.add(url="https://github.com/Company/MonoRepo", subdir="juliapkgs/Package.jl)") # With subdir
```

See also [`PackageSpec`](@ref).


In [49]:
typeof(Pkg)

Module

In [84]:
methods(hankelh1)

LoadError: UndefVarError: hankelh1 not defined